apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: acvzl2ums-nodejs 
  janus-idp.io/tekton: acvzl2ums-nodejs
  backstage.io/kubernetes-id: acvzl2ums-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: acvzl2ums-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  