apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: acvzl2ums-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acvzl2ums-nodejs 
  name: acvzl2ums-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: acvzl2ums-nodejs 
